openapi: 3.0.3
info:
  title: Figma plugin API
  version: 1.0.0
paths:
  /me:
    get:
      operationId: getMe
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  firstName:
                    type: string
                  lastName:
                    type: string
                  workspace:
                    type: object
                    additionalProperties: false
                    properties:
                      id:
                        type: string
                      name:
                        type: string
                      key:
                        type: string
                    required:
                      - id
                      - name
                      - key
                  system:
                    type: object
                    additionalProperties: false
                    properties:
                      version:
                        type: string
                      distribution:
                        type: string
                        enum:
                          - self-hosted
                          - cloud
                    required:
                      - version
                      - distribution
                additionalProperties: false
                required:
                  - id
                  - firstName
                  - lastName
                  - workspace
  /languages:
    get:
      operationId: listLanguages
      parameters:
        - name: projectId
          in: query
          description: Project ID
          required: true
          schema:
            type: string
        - name: page
          in: query
          description: Page number
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: List of languages
          content:
            application/json:
              schema:
                type: object
                properties:
                  pagination:
                    $ref: '#/components/schemas/Pagination'
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Language'
                additionalProperties: false
                required:
                  - pagination
                  - items
  /projects:
    get:
      operationId: listProjects
      parameters:
        - name: page
          in: query
          description: Page number
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: List of projects
          content:
            application/json:
              schema:
                type: object
                properties:
                  pagination:
                    $ref: '#/components/schemas/Pagination'
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Project'
                additionalProperties: false
                required:
                  - pagination
                  - items
  /figma-files:
    post:
      operationId: createFigmaFile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                revisionId:
                  type: string
                languageId:
                  type: string
                url:
                  type: string
                name:
                  type: string
              additionalProperties: false
              required:
                - revisionId
                - languageId
                - url
                - name
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FigmaFile'
  '/figma-files/{id}':
    get:
      operationId: getFigmaFile
      parameters:
        - name: id
          in: path
          description: Figma file ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FigmaFile'
    put:
      operationId: updateFigmaFile
      parameters:
        - name: id
          in: path
          description: Figma file ID
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                languageId:
                  type: string
              additionalProperties: false
              required:
                - languageId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FigmaFile'
    delete:
      operationId: deleteFigmaFile
      parameters:
        - name: id
          in: path
          description: Figma file ID
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No content
  '/figma-files/{id}/available-phrases':
    get:
      operationId: listFigmaFileAvailablePhrases
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: query
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of phrases
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/AvailablePhrase'
                additionalProperties: false
                required:
                  - items
  '/figma-files/{id}/texts':
    get:
      operationId: listFigmaFileTexts
      parameters:
        - name: id
          in: path
          description: Figma file ID
          required: true
          schema:
            type: string
        - name: pageNodeId
          in: query
          description: Page node ID
          required: true
          schema:
            type: string
        - name: page
          in: query
          description: Page number
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/FigmaText'
                  pagination:
                    $ref: '#/components/schemas/Pagination'
                additionalProperties: false
                required:
                  - items
                  - pagination
    post:
      operationId: createFigmaFileText
      parameters:
        - name: id
          in: path
          description: Figma file ID
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                items:
                  type: array
                  items:
                    oneOf:
                      - $ref: '#/components/schemas/CreateFigmaTextAndCreatePhrase'
                      - $ref: '#/components/schemas/CreateFigmaTextAndConnectPhrase'
              additionalProperties: false
              required:
                - items
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/FigmaText'
                additionalProperties: false
                required:
                  - items
  '/figma-files/{id}/texts/{textId}':
    put:
      operationId: updateFigmaFileText
      parameters:
        - name: id
          in: path
          description: Figma file ID
          required: true
          schema:
            type: string
        - name: textId
          in: path
          description: Figma text ID
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
              additionalProperties: false
              required:
                - content
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FigmaText'
  '/figma-files/{id}/prompts':
    get:
      operationId: listFigmaFilePrompts
      parameters:
        - name: id
          in: path
          description: Figma file ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Prompt'
                additionalProperties: false
                required:
                  - items
  /ai/translate:
    post:
      operationId: translate
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                workspaceId:
                  type: string
                sourceLanguageId:
                  type: string
                targetLanguageId:
                  type: string
              additionalProperties: false
              required:
                - content
                - workspaceId
                - sourceLanguageId
                - targetLanguageId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  suggestion:
                    type: string
                additionalProperties: false
                required:
                  - suggestion
  /ai/rewrite:
    post:
      operationId: rewrite
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                sourceLanguageId:
                  type: string
                promptId:
                  type: string
              additionalProperties: false
              required:
                - content
                - sourceLanguageId
                - promptId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  suggestion:
                    type: string
                additionalProperties: false
                required:
                  - suggestion
components:
  schemas:
    Empty:
      type: string
      enum:
        - null
      nullable: true
    Pagination:
      type: object
      properties:
        page:
          type: integer
        pageSize:
          type: integer
        pagesCount:
          type: integer
        itemsCount:
          type: integer
      additionalProperties: false
      required:
        - page
        - pageSize
        - pagesCount
        - itemsCount
    Project:
      type: object
      properties:
        id:
          type: string
        workspaceId:
          type: string
        name:
          type: string
        description:
          type: string
          nullable: true
        masterRevisionId:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      additionalProperties: false
      required:
        - id
        - workspaceId
        - masterRevisionId
        - name
        - description
        - createdAt
        - updatedAt
    Language:
      type: object
      properties:
        id:
          type: string
        workspaceId:
          type: string
        locale:
          type: string
        name:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      additionalProperties: false
      required:
        - id
        - workspaceId
        - locale
        - name
        - createdAt
        - updatedAt
    AvailablePhrase:
      type: object
      properties:
        id:
          type: string
        key:
          type: string
        content:
          nullable: true
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      additionalProperties: false
      required:
        - id
        - key
        - content
        - createdAt
        - updatedAt
    FigmaFile:
      type: object
      properties:
        id:
          type: string
        workspaceId:
          type: string
        revisionId:
          type: string
        languageId:
          type: string
        projectId:
          type: string
        projectName:
          type: string
        languageName:
          type: string
        key:
          type: string
        url:
          type: string
        inAppUrl:
          type: string
        name:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      additionalProperties: false
      required:
        - id
        - workspaceId
        - revisionId
        - languageId
        - projectId
        - projectName
        - languageName
        - key
        - url
        - inAppUrl
        - name
        - createdAt
        - updatedAt
    FigmaText:
      type: object
      properties:
        id:
          type: string
        fileId:
          type: string
        workspaceId:
          type: string
        phraseId:
          type: string
        phraseKey:
          type: string
        textNodeId:
          type: string
        pageNodeId:
          type: string
        content:
          nullable: true
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      additionalProperties: false
      required:
        - id
        - fileId
        - workspaceId
        - phraseId
        - phraseKey
        - textNodeId
        - pageNodeId
        - content
        - createdAt
        - updatedAt
    CreateFigmaTextAndCreatePhrase:
      type: object
      properties:
        phraseKey:
          type: string
          nullable: true
        content:
          type: string
        textNodeId:
          type: string
        pageNodeId:
          type: string
      additionalProperties: false
      required:
        - phraseKey
        - textNodeId
        - pageNodeId
        - content
    CreateFigmaTextAndConnectPhrase:
      type: object
      properties:
        phraseId:
          type: string
        textNodeId:
          type: string
        pageNodeId:
          type: string
      additionalProperties: false
      required:
        - phraseId
        - textNodeId
        - pageNodeId
    PromptTone:
      type: string
      enum:
        - professional
        - casual
        - playful
        - conversational
    PromptLength:
      type: string
      enum:
        - shorter
        - longer
        - same
    Prompt:
      type: object
      properties:
        id:
          type: string
        default:
          type: boolean
        workspaceId:
          type: string
        glossaryId:
          type: string
          nullable: true
        name:
          type: string
        description:
          type: string
          nullable: true
        tone:
          oneOf:
            - $ref: '#/components/schemas/PromptTone'
            - $ref: '#/components/schemas/Empty'
        length:
          oneOf:
            - $ref: '#/components/schemas/PromptLength'
            - $ref: '#/components/schemas/Empty'
        customInstructions:
          type: array
          items:
            type: string
      additionalProperties: false
      required:
        - id
        - default
        - workspaceId
        - glossaryId
        - name
        - description
        - tone
        - length
        - customInstructions
