openapi: 3.0.3
info:
  title: Figma plugin API
  version: 1.0.0
paths:
  /Ping:
    get:
      operationId: getPing
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                additionalProperties: false
                required:
                  - name
