openapi: 3.0.3
info:
  title: Private API
  version: 1.0.0
paths:
  /hello-world:
    get:
      summary: Hello World
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Hello, World!'
