version: '3.8'
services:
  app:
    platform: linux/x86_64
    image: recontentapp/recontentapp:latest
    restart: always
    depends_on:
      migrate:
        condition: service_completed_successfully
    ports:
      - '3000:3000'
    environment:
      - S3_BUCKET_NAME=
      - DATABASE_LOG_QUERIES=false
      - S3_SECRET_ACCESS_KEY=
      - APP_URL=
      - S3_BUCKET_URL=
      - DATABASE_URL=postgresql://postgres:postgres@localhost:5432/recontentapp
      - WORKSPACE_INVITE_ONLY=false
      - APP_VERSION=0.4.2
      - S3_ENDPOINT=
      - API_URL=
      - MAILER_USER=
      - S3_ACCESS_KEY_ID=
      - PORT=3000
      - MAILER_SECURE=false
      - MAILER_PASSWORD=
      - S3_REGION=
      - MAILER_FROM_EMAIL=
      - JWT_SECRET=
      - MAILER_PORT=
      - ENCRYPTION_KEY=
      - MAILER_HOST=
      - NODE_ENV=production
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/healthz']
      interval: 30s
      timeout: 10s
      retries: 5
  migrate:
    platform: linux/x86_64
    image: recontentapp/recontentapp-migrate:latest
    restart: on-failure
    depends_on:
      postgres:
        condition: service_started
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/recontentapp
  postgres:
    image: postgres:16.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=recontentapp
    ports:
      - '6033:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
    driver: local
