version: '3.8'
services:
  db:
    image: postgres:16.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=recontentapp
    ports:
      - '6033:5432'
    volumes:
      - db:/var/lib/postgresql/data
  maildev:
    image: maildev/maildev
    ports:
      - '1080:1080'
      - '1025:1025'
  localstack:
    image: localstack/localstack
    ports:
      - '4566:4566' # LocalStack Gateway
      - '4510-4559:4510-4559' # external services port range
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - localstack_storage:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  localstack_storage:
    driver: local
  db:
    driver: local
