// https://documentation.mjml.io/#mj-divider
export const attributes: Record<string, string[]> = {
  mjml: ['lang'],
  'mj-head': [],
  'mj-font': ['href', 'name'],
  'mj-style': ['inline'],
  'mj-button': [
    'align',
    'background-color',
    'border',
    'border-bottom',
    'border-left',
    'border-radius',
    'border-right',
    'border-top',
    'color',
    'container-background-color',
    'css-class',
    'font-family',
    'font-size',
    'font-style',
    'font-weight',
    'height',
    'inner-padding',
    'letter-spacing',
    'line-height',
    'padding',
    'padding-bottom',
    'padding-top',
    'padding-left',
    'padding-right',
    'rel',
    'target',
    'text-align',
    'text-decoration',
    'text-transform',
    'title',
    'vertical-align',
    'width',
  ],
  'mj-column': [
    'background-color',
    'inner-background-color',
    'border',
    'border-bottom',
    'border-left',
    'border-radius',
    'border-right',
    'border-top',
    'inner-border',
    'inner-border-bottom',
    'inner-border-left',
    'inner-border-radius',
    'inner-border-right',
    'inner-border-top',
    'vertical-align',
    'width',
    'padding',
    'padding-bottom',
    'padding-top',
    'padding-left',
    'padding-right',
    'css-class',
  ],
}
