name: Continuous deployment

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

env:
  APP_IMAGE_NAME: recontentapp/recontentapp
  MIGRATE_IMAGE_NAME: recontentapp/recontentapp-migrate

jobs:
  app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.APP_IMAGE_NAME }}
          labels: |
            org.opencontainers.image.title="Recontent.app"
            org.opencontainers.image.source=https://github.com/recontentapp/recontentapp
            org.opencontainers.image.url=https://github.com/recontentapp/recontentapp
            org.opencontainers.image.licenses="AGPL-3.0-or-later"
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: docker/Dockerfile
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.MIGRATE_IMAGE_NAME }}
          labels: |
            org.opencontainers.image.title="Recontent.app - Migrate"
            org.opencontainers.image.source=https://github.com/recontentapp/recontentapp
            org.opencontainers.image.url=https://github.com/recontentapp/recontentapp
            org.opencontainers.image.licenses="AGPL-3.0-or-later"
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: docker/Dockerfile.migrate
